### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kapbl** [ZhangXu0963/NPC#1]
image = self.preprocess(Image.open(os.path.join(self.image_root, self.image_name[idx]))) # Image from PIL module
在这里一行会出现索引过长的问题，请问这是什么原因？俺没找出来原因（很菜的程序技术），露怯了，哈哈哈。

**Comment by kapbl** [comment]
我知道了 我知道了 在params.py中没设置妥当

**Comment by ZhangXu0963** [comment]
解决了就好，欢迎随时提问 : )
