### ISSUE TITLE
get_memorybank

### ISSUE THREAD

**Issue by LuLu1226** [ZhangXu0963/NPC#10]
您好！不好意思再次打扰您了！我在执行get_memorybank.py 时出现下列错误，想向您求教：
![捕获5](https://github.com/ZhangXu0963/NPC/assets/168350490/c9572bd5-b92e-4c29-b446-576636242115)

下面是错误代码：
![捕获2](https://github.com/ZhangXu0963/NPC/assets/168350490/8e76b149-d55d-4fce-81ef-39d8e88261ff)

**Comment by kapbl** [comment]
似乎是正确的（按照batch返回的值来看），刚好对应images, img_ids, texts, txt_ids,_,_,_,_

**Comment by kapbl** [comment]
可以互相加一个联系方式吗？我俩可以展开讨论，我的QQ号183802648，期待你的来访

**Comment by LuLu1226** [comment]
> 



> 可以互相加一个联系方式吗？我俩可以展开讨论，我的QQ号183802648，期待你的来访

好的

**Comment by LuLu1226** [comment]
我知道了，索引越界错误是由于dataloader中丢弃了最后一个batch数据所导致的

**Comment by qxzha** [comment]
@LuLu1226  hi, if this issue is fixed, could you please provide the codes ?
