### ISSUE TITLE
best model

### ISSUE THREAD

**Issue by LuoXiaoBai965** [ZhangXu0963/NPC#11]
您好!打扰您了,请问我在噪声比为 0.2 的时候进行训练时, 随着epoch的增加模型反而越来越差是为什么? 过拟合了吗? 下图指标最好的是第1个epoch的时候, 然后继续训练指标反而下降, 而且降得挺多的.
![捕获1](https://github.com/ZhangXu0963/NPC/assets/52725784/5aadc8e6-6987-4158-b8f1-f0bc62db4df1)
![捕获2](https://github.com/ZhangXu0963/NPC/assets/52725784/24bba3be-8806-4681-bf8f-b62d04f3e5a3)
![捕获4](https://github.com/ZhangXu0963/NPC/assets/52725784/90046d97-b7bc-41cb-b9c5-9ae494e8a43a)
![捕获5](https://github.com/ZhangXu0963/NPC/assets/52725784/bce7d3e8-2661-41c9-9aa6-26b6b0a1677e)

**Comment by ZhangXu0963** [comment]
是的，会出现过拟合的现象，因为CLIP本身是预训练过的，用NPC来fintuning会收敛的更快些，每个epoch之后都会保存模型，你可以只取epoch1的model来用。
