### ISSUE TITLE
missing image_name.txt in flickr30k dataset

### ISSUE THREAD

**Issue by xunxiaorenb612** [ZhangXu0963/NPC#12]
Hello! We are very interested in your work. However, when trying to reproduce the code, we found that “image_name.txt” in flickr30k datase is missing. We didn't find it in the links, could you please provide it for us?
![image](https://github.com/user-attachments/assets/de5ed6c7-0428-4672-90f4-92979b93b1e1)

**Comment by ZhangXu0963** [comment]
You can get the full dataset (except images) in these links in README.md.
![image](https://github.com/user-attachments/assets/d6843c9e-fc4a-4c67-998a-1022831abb8e)
And here is the directory tree of Flickr30K provided in the link.
![image](https://github.com/user-attachments/assets/67367957-793c-433b-87d8-4533df9c698f)
