### ISSUE TITLE
Inconsistent Data Loading Methods from DataLoader in get_memorybank? 

### ISSUE THREAD

**Issue by MiSanl** [ZhangXu0963/NPC#14]
First data loading:
https://github.com/ZhangXu0963/NPC/blob/04d8e79945fac9e13689d53efa46d39d11743854/get_memorybank.py#L29
Second data loading:
https://github.com/ZhangXu0963/NPC/blob/04d8e79945fac9e13689d53efa46d39d11743854/get_memorybank.py#L80

Why is the variable order different when loading a batch of data from the same DataLoader? Is there a mistake in the code?

**Comment by ZhangXu0963** [comment]
Sorry for replying you late. Maybe I made a mistake when I was organizing the code. Actually, this part was originally two functions when I done experiments in the paper. For the convenience of code reading, I combined them into one. I will release a modified version later. Sorry for the inconvenience.
