### ISSUE TITLE
images

### ISSUE THREAD

**Issue by LuoXiaoBai965** [ZhangXu0963/NPC#4]
您好!我想请问MSCOCO数据集的images文件里的结构是什么样的?是直接存放所有图片?还是分tarin,val,test三个文件来存放?
然后关于CC120K数据集,可不可以麻烦您发送到我的邮箱hxdafsax@gmail.com

**Comment by ZhangXu0963** [comment]
直接存放所有图片。

**Comment by ZhangXu0963** [comment]
我在readme里更新了CC120K的下载链接。

**Comment by LuoXiaoBai965** [comment]
> 我在readme里更新了CC120K的下载链接。

好的,谢谢您!
