### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by DongChenwei2000** [ZhangXu0963/NPC#5]
Hi, thank you for your excellent work. 
I have a question about reproducing your work. Have you used pre trained models before fine-tuning them? I know you have provided those models for evaluation, and by that, I mean whether pre trained models were used to partition noise based on loss values and whether NPC was trained.

**Comment by ZhangXu0963** [comment]
We use the pre-trained model before fine-tuning it. But it's not used to partition the noise set. The idea in paper is not to pick out a noise set and perform some special processing on it. 
I'm not sure what's the meaning of "whether NPC was trained". Models we provided have been already fine-tuned by NPC(ours) or CLIP(baseline) on training dataset with different noise ratio. For example, `npc_coco_20.pt` is the model fine-tuned by NPC on MSCOCO training set with 20% noise. 
Hope you found this helpful.

**Comment by DongChenwei2000** [comment]
Sorry, there may be some issues with my expression. What I mean is, did you load a pre trained model when training NPC? From your answer above, it seems that it has been loaded. Can you tell me where your pre trained model comes from? Anyway, this job is great. Thank you again.

**Comment by DongChenwei2000** [comment]
> We use the pre-trained model before fine-tuning it. But it's not used to partition the noise set. The idea in paper is not to pick out a noise set and perform some special processing on it. I'm not sure what's the meaning of "whether NPC was trained". Models we provided have been already fine-tuned by NPC(ours) or CLIP(baseline) on training dataset with different noise ratio. For example, `npc_coco_20.pt` is the model fine-tuned by NPC on MSCOCO training set with 20% noise. Hope you found this helpful.

Alright, I got it. When I actually ran it, I found that the program automatically downloaded the pre trained model. However, I also trained on a single RTX 3090 GPU, and encountered CUDA out of memory issues. Is there a problem with my settings?
![image](https://github.com/ZhangXu0963/NPC/assets/71364549/b8a2fa6b-bc5e-4768-be36-726ed5e3ffa2)

**Comment by ZhangXu0963** [comment]
I'll show you the log file of training later. I need some time to re-run my code.
