### ISSUE TITLE
get_memorybank

### ISSUE THREAD

**Issue by LuLu1226** [ZhangXu0963/NPC#7]
您好！我发现data.py文件中，您是直接加载 frozen Memory Bank 的。如果我想构建新的 memory bank，请问我该如何使用您提供的 get_memorybank.py？例如：该在哪里调用它呢？

**Comment by ZhangXu0963** [comment]
在readme中提到了如何构建自己的memorybank。其他的可以参考这个issue：https://github.com/ZhangXu0963/NPC/issues/6

**Comment by LuLu1226** [comment]
感谢您的回答！我会试着来构建mbank，但我代码能力太差了，有困难我再来向您请教。

**Comment by ZhangXu0963** [comment]
互相学习，祝您顺利。
