### ISSUE TITLE
clean_idx = np.array(clean_idx)

### ISSUE THREAD

**Issue by kapbl** [ZhangXu0963/NPC#8]
您好，谢谢您对这篇论文的贡献。请问，在get_memorybank.py的文件中 clean_idx = np.array(clean_idx)这一行语句中出现了clean_idx未定义就使用的错误，请问原本的clean_idx在上文中应该是什么？
----谢谢
----期待您的解惑！

**Comment by ZhangXu0963** [comment]
这应该是之前整理代码变量名时的疏漏，抱歉。我对get_memorybank.py做了修改，clean_idx在line61被定义。

**Comment by kapbl** [comment]
感谢您的回答。😊
